name: realtime_db
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  firebase_database: ^10.0.15
  flutter_phone_direct_caller: ^2.1.1
  path: ^1.8.2
  image_picker: ^0.8.7+3
  firebase_storage: ^11.1.1
  firebase_app_check: ^0.1.2+2
  flutter_widgets: ^0.1.12
  firebase_analytics: ^10.2.1
  firebase: ^9.0.3
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true